version: 2
jobs:

  deps:
    working_directory: ~/pushi
    docker:
      - image: circleci/clojure:lein-2.7.1
    environment:
          JVM_OPTS: -Xmx3200m
          LEIN_ROOT: nbd
    steps:
      - checkout
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: pushi-{{ checksum "project.clj" }}

  test:
    working_directory: ~/pushi
    docker:
      - image: circleci/clojure:lein-2.7.1
    environment:
          JVM_OPTS: -Xmx3200m
          LEIN_ROOT: nbd
    steps:
      - checkout
      - restore_cache:
          key: pushi-{{ checksum "project.clj" }}
      - lein do test

  build:
    working_directory: ~/pushi
    docker:
      - image: circleci/clojure:lein-2.7.1
    environment:
          JVM_OPTS: -Xmx3200m
          LEIN_ROOT: nbd
    steps:
      - checkout
      - restore_cache:
          key: pushi-{{ checksum "project.clj" }}
      - run: lein uberjar

workflows:
  version: 2
  deps_then_test_and_build:
    jobs:
      - deps
      - test:
          requires:
            - deps
      - build:
          requires:
            - deps
